/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimestampRouteImport } from './routes/timestamp'
import { Route as TimerRouteImport } from './routes/timer'
import { Route as SetsRouteImport } from './routes/sets'
import { Route as ScratchpadRouteImport } from './routes/scratchpad'
import { Route as RegexRouteImport } from './routes/regex'
import { Route as ReadabilityRouteImport } from './routes/readability'
import { Route as RandomizerRouteImport } from './routes/randomizer'
import { Route as QrRouteImport } from './routes/qr'
import { Route as MoonRouteImport } from './routes/moon'
import { Route as JqRouteImport } from './routes/jq'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CounterRouteImport } from './routes/counter'
import { Route as ContrastRouteImport } from './routes/contrast'
import { Route as ColorRouteImport } from './routes/color'
import { Route as CapitalizeRouteImport } from './routes/capitalize'
import { Route as BmiRouteImport } from './routes/bmi'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TimestampRoute = TimestampRouteImport.update({
  id: '/timestamp',
  path: '/timestamp',
  getParentRoute: () => rootRouteImport,
} as any)
const TimerRoute = TimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => rootRouteImport,
} as any)
const SetsRoute = SetsRouteImport.update({
  id: '/sets',
  path: '/sets',
  getParentRoute: () => rootRouteImport,
} as any)
const ScratchpadRoute = ScratchpadRouteImport.update({
  id: '/scratchpad',
  path: '/scratchpad',
  getParentRoute: () => rootRouteImport,
} as any)
const RegexRoute = RegexRouteImport.update({
  id: '/regex',
  path: '/regex',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadabilityRoute = ReadabilityRouteImport.update({
  id: '/readability',
  path: '/readability',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomizerRoute = RandomizerRouteImport.update({
  id: '/randomizer',
  path: '/randomizer',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const MoonRoute = MoonRouteImport.update({
  id: '/moon',
  path: '/moon',
  getParentRoute: () => rootRouteImport,
} as any)
const JqRoute = JqRouteImport.update({
  id: '/jq',
  path: '/jq',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CounterRoute = CounterRouteImport.update({
  id: '/counter',
  path: '/counter',
  getParentRoute: () => rootRouteImport,
} as any)
const ContrastRoute = ContrastRouteImport.update({
  id: '/contrast',
  path: '/contrast',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorRoute = ColorRouteImport.update({
  id: '/color',
  path: '/color',
  getParentRoute: () => rootRouteImport,
} as any)
const CapitalizeRoute = CapitalizeRouteImport.update({
  id: '/capitalize',
  path: '/capitalize',
  getParentRoute: () => rootRouteImport,
} as any)
const BmiRoute = BmiRouteImport.update({
  id: '/bmi',
  path: '/bmi',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bmi': typeof BmiRoute
  '/capitalize': typeof CapitalizeRoute
  '/color': typeof ColorRoute
  '/contrast': typeof ContrastRoute
  '/counter': typeof CounterRoute
  '/events': typeof EventsRoute
  '/jq': typeof JqRoute
  '/moon': typeof MoonRoute
  '/qr': typeof QrRoute
  '/randomizer': typeof RandomizerRoute
  '/readability': typeof ReadabilityRoute
  '/regex': typeof RegexRoute
  '/scratchpad': typeof ScratchpadRoute
  '/sets': typeof SetsRoute
  '/timer': typeof TimerRoute
  '/timestamp': typeof TimestampRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bmi': typeof BmiRoute
  '/capitalize': typeof CapitalizeRoute
  '/color': typeof ColorRoute
  '/contrast': typeof ContrastRoute
  '/counter': typeof CounterRoute
  '/events': typeof EventsRoute
  '/jq': typeof JqRoute
  '/moon': typeof MoonRoute
  '/qr': typeof QrRoute
  '/randomizer': typeof RandomizerRoute
  '/readability': typeof ReadabilityRoute
  '/regex': typeof RegexRoute
  '/scratchpad': typeof ScratchpadRoute
  '/sets': typeof SetsRoute
  '/timer': typeof TimerRoute
  '/timestamp': typeof TimestampRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bmi': typeof BmiRoute
  '/capitalize': typeof CapitalizeRoute
  '/color': typeof ColorRoute
  '/contrast': typeof ContrastRoute
  '/counter': typeof CounterRoute
  '/events': typeof EventsRoute
  '/jq': typeof JqRoute
  '/moon': typeof MoonRoute
  '/qr': typeof QrRoute
  '/randomizer': typeof RandomizerRoute
  '/readability': typeof ReadabilityRoute
  '/regex': typeof RegexRoute
  '/scratchpad': typeof ScratchpadRoute
  '/sets': typeof SetsRoute
  '/timer': typeof TimerRoute
  '/timestamp': typeof TimestampRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bmi'
    | '/capitalize'
    | '/color'
    | '/contrast'
    | '/counter'
    | '/events'
    | '/jq'
    | '/moon'
    | '/qr'
    | '/randomizer'
    | '/readability'
    | '/regex'
    | '/scratchpad'
    | '/sets'
    | '/timer'
    | '/timestamp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bmi'
    | '/capitalize'
    | '/color'
    | '/contrast'
    | '/counter'
    | '/events'
    | '/jq'
    | '/moon'
    | '/qr'
    | '/randomizer'
    | '/readability'
    | '/regex'
    | '/scratchpad'
    | '/sets'
    | '/timer'
    | '/timestamp'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bmi'
    | '/capitalize'
    | '/color'
    | '/contrast'
    | '/counter'
    | '/events'
    | '/jq'
    | '/moon'
    | '/qr'
    | '/randomizer'
    | '/readability'
    | '/regex'
    | '/scratchpad'
    | '/sets'
    | '/timer'
    | '/timestamp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BmiRoute: typeof BmiRoute
  CapitalizeRoute: typeof CapitalizeRoute
  ColorRoute: typeof ColorRoute
  ContrastRoute: typeof ContrastRoute
  CounterRoute: typeof CounterRoute
  EventsRoute: typeof EventsRoute
  JqRoute: typeof JqRoute
  MoonRoute: typeof MoonRoute
  QrRoute: typeof QrRoute
  RandomizerRoute: typeof RandomizerRoute
  ReadabilityRoute: typeof ReadabilityRoute
  RegexRoute: typeof RegexRoute
  ScratchpadRoute: typeof ScratchpadRoute
  SetsRoute: typeof SetsRoute
  TimerRoute: typeof TimerRoute
  TimestampRoute: typeof TimestampRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timestamp': {
      id: '/timestamp'
      path: '/timestamp'
      fullPath: '/timestamp'
      preLoaderRoute: typeof TimestampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timer': {
      id: '/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof TimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sets': {
      id: '/sets'
      path: '/sets'
      fullPath: '/sets'
      preLoaderRoute: typeof SetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scratchpad': {
      id: '/scratchpad'
      path: '/scratchpad'
      fullPath: '/scratchpad'
      preLoaderRoute: typeof ScratchpadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regex': {
      id: '/regex'
      path: '/regex'
      fullPath: '/regex'
      preLoaderRoute: typeof RegexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readability': {
      id: '/readability'
      path: '/readability'
      fullPath: '/readability'
      preLoaderRoute: typeof ReadabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/randomizer': {
      id: '/randomizer'
      path: '/randomizer'
      fullPath: '/randomizer'
      preLoaderRoute: typeof RandomizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moon': {
      id: '/moon'
      path: '/moon'
      fullPath: '/moon'
      preLoaderRoute: typeof MoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jq': {
      id: '/jq'
      path: '/jq'
      fullPath: '/jq'
      preLoaderRoute: typeof JqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counter': {
      id: '/counter'
      path: '/counter'
      fullPath: '/counter'
      preLoaderRoute: typeof CounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contrast': {
      id: '/contrast'
      path: '/contrast'
      fullPath: '/contrast'
      preLoaderRoute: typeof ContrastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color': {
      id: '/color'
      path: '/color'
      fullPath: '/color'
      preLoaderRoute: typeof ColorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capitalize': {
      id: '/capitalize'
      path: '/capitalize'
      fullPath: '/capitalize'
      preLoaderRoute: typeof CapitalizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bmi': {
      id: '/bmi'
      path: '/bmi'
      fullPath: '/bmi'
      preLoaderRoute: typeof BmiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BmiRoute: BmiRoute,
  CapitalizeRoute: CapitalizeRoute,
  ColorRoute: ColorRoute,
  ContrastRoute: ContrastRoute,
  CounterRoute: CounterRoute,
  EventsRoute: EventsRoute,
  JqRoute: JqRoute,
  MoonRoute: MoonRoute,
  QrRoute: QrRoute,
  RandomizerRoute: RandomizerRoute,
  ReadabilityRoute: ReadabilityRoute,
  RegexRoute: RegexRoute,
  ScratchpadRoute: ScratchpadRoute,
  SetsRoute: SetsRoute,
  TimerRoute: TimerRoute,
  TimestampRoute: TimestampRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
