/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimestampRouteImport } from './routes/timestamp'
import { Route as TimerRouteImport } from './routes/timer'
import { Route as ScratchpadRouteImport } from './routes/scratchpad'
import { Route as ColorRouteImport } from './routes/color'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TimestampRoute = TimestampRouteImport.update({
  id: '/timestamp',
  path: '/timestamp',
  getParentRoute: () => rootRouteImport,
} as any)
const TimerRoute = TimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => rootRouteImport,
} as any)
const ScratchpadRoute = ScratchpadRouteImport.update({
  id: '/scratchpad',
  path: '/scratchpad',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorRoute = ColorRouteImport.update({
  id: '/color',
  path: '/color',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/color': typeof ColorRoute
  '/scratchpad': typeof ScratchpadRoute
  '/timer': typeof TimerRoute
  '/timestamp': typeof TimestampRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/color': typeof ColorRoute
  '/scratchpad': typeof ScratchpadRoute
  '/timer': typeof TimerRoute
  '/timestamp': typeof TimestampRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/color': typeof ColorRoute
  '/scratchpad': typeof ScratchpadRoute
  '/timer': typeof TimerRoute
  '/timestamp': typeof TimestampRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/color' | '/scratchpad' | '/timer' | '/timestamp'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/color' | '/scratchpad' | '/timer' | '/timestamp'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/color'
    | '/scratchpad'
    | '/timer'
    | '/timestamp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ColorRoute: typeof ColorRoute
  ScratchpadRoute: typeof ScratchpadRoute
  TimerRoute: typeof TimerRoute
  TimestampRoute: typeof TimestampRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timestamp': {
      id: '/timestamp'
      path: '/timestamp'
      fullPath: '/timestamp'
      preLoaderRoute: typeof TimestampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timer': {
      id: '/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof TimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scratchpad': {
      id: '/scratchpad'
      path: '/scratchpad'
      fullPath: '/scratchpad'
      preLoaderRoute: typeof ScratchpadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color': {
      id: '/color'
      path: '/color'
      fullPath: '/color'
      preLoaderRoute: typeof ColorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ColorRoute: ColorRoute,
  ScratchpadRoute: ScratchpadRoute,
  TimerRoute: TimerRoute,
  TimestampRoute: TimestampRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
